title: Lynn Cyrin
email: lynncyrin@gmail.com
description: >
  Python / Ruby Web Developer and Project Manager + Activist
baseurl: ""
url: "http://lynncyrin.me"

permalink: pretty
markdown: kramdown
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
    style: compressed
    sass_dir: _sass
