title: Lynn Cyrin
email: lynncyrin@gmail.com
description: >
  Full Stack Web Developer, Activist, and QTWoC. Founder of
  CollectQT Likes: Websites Python, Rails, Open Source,
  Premature Optimizations, Gaming, Space, Sex work, Being
  Gay
baseurl: ""
url: "http://lynncyrin.me"
twitter_username: lynncyrin
github_username:  lynnco

markdown: kramdown
gems:
  - jemoji
