title: Lynn Cyrin
email: lynncyrin@gmail.com
description: >
  Ruby / Python Web Developer and Project Manager + Activist
baseurl: ""
url: "http://lynncyrin.me"
twitter_username: lynncyrin
github_username:  lynnco

permalink: pretty
markdown: kramdown
gems:
  - jemoji

sass:
    style: compressed
    sass_dir: _sass
